### ISSUE TITLE
What should be the default behavior of the back button?

### ISSUE THREAD

**Issue by simsarulhaqv** [fosscell/2017#10]

**Comment by yashhere** [comment]
I have added some new settings to control over scrolling. I think that was the issue you were facing.

**Comment by SpEcHiDe** [comment]
When you click or scroll down the navigation, a location hash is appended to the URL. 
So, when we click on back button, the default behavior should be to go to the previous page. 
But, in the above website, the default behavior is to go back the sections that are scrolled down.

This can be put to a "vote", by which we can decide which default behavior we want?

Reference: 
- [Link One](https://madhatted.com/2013/6/16/you-do-not-understand-browser-history)

**Comment by yashhere** [comment]
So, I can remove those anchors from the url, and back button also works in that case. But I don't know whether this will have any other issue. Please check.

P.S. :- Back button functionality was removed from chrome after v52

**Comment by yashhere** [comment]
It disables the navbar also. So that is not an option.

**Comment by SpEcHiDe** [comment]
Thank you @anasanzari
