### ISSUE TITLE
List of Social Networks to be included

### ISSUE THREAD

**Issue by SpEcHiDe** [fosscell/2017#11]
- [FaceBook](https://www.facebook.com/fossmeet)
- [Twitter](https://twitter.com/fossmeet)
- [Google Groups](https://groups.google.com/forum/#!forum/fossmeetnitc)
- [Diaspora*](https://poddery.com/u/fossmeet)
- [YouTube](https://www.youtube.com/channel/UCwfNynjOSd3oPwIFqduJ9-Q)
- [Flickr](http://www.flickr.com/search/?q=fossmeet)

**Comment by SpEcHiDe** [comment]
- [Twitter](https://twitter.com/fosscell)
- [Google Groups](https://groups.google.com/forum/#!forum/nitcosc)

**Comment by pbhopalka** [comment]
Do we have Flickr? Otherwise, it looks sufficient.

**Comment by SpEcHiDe** [comment]
<a href="mailto:fossmeet@poddery.com" class="fa fa-diasp">

Diaspora
                          </a>
                          <a href="https://fb.me/FOSSMeet" class="fa fa-facebook fa-2x"><span class="label">Facebook</span></a>
                          <a href="http://www.flickr.com/search/?q=fossmeet" class="fa fa-flickr fa-2x"><span class="label">Flickr</span></a>
                          <a href="https://github.com/fosscell" class="fa fa-github fa-2x"><span class="label">GitHub</span></a>
                          <a href="https://gitlab.com/groups/fosscell" class="fa fa-gitlab fa-2x"><span class="label">GitLab</span></a>
                          <a href="https://plus.google.com/109660182976357345132" class="fa fa-google-plus fa-2x"><span class="label">Google+</span></a>
                          <a href="https://twitter.com/fossmeet" class="fa fa-twitter fa-2x"><span class="label">Twitter</span></a>
                          <a href="https://www.youtube.com/channel/UCwfNynjOSd3oPwIFqduJ9-Q" class="fa fa-youtube fa-2x"><span class="label">YouTube</span></a>

**Comment by aashishsatya** [comment]
That'll be enough right? I think you'll know better if there are any.

**Comment by SpEcHiDe** [comment]
Which ones to be included in the website?

**Comment by SpEcHiDe** [comment]
Currently, including Diaspora*, faceBook, Flickr, Twitter and YouTube !
