### ISSUE TITLE
new FOSS logo

### ISSUE THREAD

**Issue by SpEcHiDe** [fosscell/2017#14]
@fosscell/design17 please design a new FOSSMeet logo consistent with the color scheme!

Try to make it in SVG as suggested by @krisaju95

**Comment by pbhopalka** [comment]
We will look into this issue. We are yet to decide if we do require a change in logo. We will provide the SVG

**Comment by SpEcHiDe** [comment]
<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="300pt" height="400pt" viewBox="0 0 480 480" preserveAspectRatio="xMidYMid meet">
<g transform="translate(0.000000,480.000000) scale(0.100000,-0.100000)" stroke="none">
    <path d="M1796 4725 c-43 -124 -129 -278 -219 -393 -45 -57 -91 -117 -102                 -132 -40 -55 -195 -227 -286 -317 -142 -139 -212 -225 -294 -362 -102 -172                 -141 -279 -165 -457 -10 -70 -10 -110 -1 -179 13 -96 45 -238 66 -294 7 -20                 23 -67 35 -106 25 -82 111 -249 182 -355 136 -202 383 -466 537 -576 116 -82                 192 -134 197 -134 2 0 34 -19 71 -43 38 -24 73 -46 80 -50 23 -14 -63 118                 -112 172 -228 252 -301 360 -434 636 -81 169 -88 189 -107 285 -36 189 -3 405                 90 589 29 56 206 322 246 367 32 37 227 349 265 424 40 79 73 171 82 227 14                 91 6 206 -18 262 l-22 52 -24 -91 c-44 -170 -117 -307 -254 -476 -92 -113                 -299 -278 -299 -238 0 10 55 78 113 138 33 34 76 84 97 111 21 28 57 74 80                 104 58 74 156 247 165 290 2 9 13 41 25 71 47 124 68 335 48 470 l-13 85 -29                 -80z"/>
    <path d="M2540 4770 c-152 -42 -226 -90 -323 -213 -101 -128 -163 -259 -172                 -369 -13 -150 -34 -355 -40 -381 -12 -60 -58 -185 -95 -262 -25 -52 -68 -113                 -121 -175 -114 -132 -241 -303 -282 -380 -34 -64 -83 -189 -91 -233 -25 -139                 -29 -209 -17 -288 7 -46 14 -94 16 -106 5 -36 55 -184 81 -241 13 -29 24 -54                 24 -57 0 -2 17 -32 37 -67 51 -88 174 -249 258 -338 39 -41 107 -118 152 -170                 125 -148 181 -196 247 -215 77 -23 124 -13 178 35 38 33 73 91 92 153 10 32                 26 17 26 -25 0 -28 -11 -60 -35 -104 -20 -35 -40 -66 -45 -69 -6 -3 -10 -11                 -10 -17 0 -18 90 -2 155 27 97 43 248 167 380 315 114 126 217 296 252 413 8                 29 18 57 23 62 11 14 56 193 76 300 20 112 14 299 -14 432 -36 163 -134 358                 -333 661 -205 311 -227 353 -320 602 -23 64 -69 275 -69 320 0 67 16 131 50                 206 37 81 77 125 141 154 l52 25 -59 12 c-80 16 -136 15 -214 -7z m-5 -1526                 c196 -34 354 -116 486 -251 97 -99 121 -143 154 -278 25 -101 26 -116 16 -185                 -6 -41 -22 -113 -36 -160 -26 -84 -27 -86 -130 -187 -109 -107 -182 -152 -330                 -203 -178 -62 -457 -65 -680 -7 -94 24 -133 42 -223 104 -247 169 -351 410                 -283 657 43 157 173 310 342 403 109 60 180 85 299 107 157 28 219 28 385 0z"/>
    <path d="M2944 4746 c-143 -45 -220 -185 -218 -396 1 -65 7 -122 16 -150 9                 -25 19 -58 23 -74 17 -75 162 -337 261 -471 24 -33 47 -67 51 -75 3 -8 30 -51                 58 -95 150 -231 207 -360 272 -605 26 -101 27 -114 28 -365 0 -254 -1 -263                 -29 -375 -47 -189 -94 -302 -179 -440 -84 -134 -200 -258 -309 -329 -37 -25                 -66 -46 -64 -48 9 -9 203 50 267 82 90 46 128 74 198 145 114 117 175 212 241                 376 121 296 153 618 94 952 -33 186 -162 501 -245 597 -9 11 -32 45 -51 76                 -33 55 -46 74 -123 173 -99 127 -251 359 -295 451 -49 101 -64 180 -56 304 5                 77 11 107 36 160 17 36 34 68 38 71 17 13 44 50 36 49 -5 0 -27 -6 -50 -13z"/>
    <path d="M3227 4615 c-22 -7 -50 -24 -64 -37 -49 -45 -76 -143 -64 -228 25                 -161 85 -292 224 -490 153 -218 278 -442 360 -645 36 -88 107 -318 113 -362 2                 -21 9 -62 14 -92 13 -70 12 -266 -1 -356 -5 -38 -12 -84 -14 -101 -7 -54 -56                 -225 -87 -303 -57 -144 -112 -235 -237 -390 -123 -152 -155 -195 -140 -186 8                 5 57 40 109 78 115 85 263 231 316 312 21 33 42 62 45 65 10 7 76 143 100 203                 26 64 57 170 65 217 3 19 12 66 20 103 40 194 -2 487 -113 787 -43 115 -189                 416 -235 485 -81 120 -127 186 -191 275 -124 173 -237 420 -237 516 0 62 9 85                 53 132 34 35 25 39 -36 17z"/>
    <path d="M146 1974 c-9 -23 -7 -52 3 -56 4 -1 97 -136 206 -298 108 -162 205                 -304 215 -315 10 -11 45 -61 78 -111 63 -95 213 -276 274 -331 26 -23 67 -41                 154 -67 66 -20 175 -54 244 -76 69 -22 157 -49 196 -60 38 -11 81 -28 94 -37                 l23 -16 -7 -169 -7 -168 281 0 280 0 0 324 c0 247 -3 326 -12 333 -7 5 -51 25                 -98 43 -47 18 -105 43 -130 56 -25 12 -83 39 -130 60 -47 20 -103 45 -125 54                 -56 25 -235 96 -265 105 -62 18 -407 188 -492 242 -42 26 -112 70 -155 97 -76                 47 -127 84 -325 232 -227 171 -285 201 -302 158z"/>
    <path d="M4582 1968 c-24 -13 -110 -72 -192 -133 -356 -265 -490 -351 -745                 -474 -110 -54 -216 -103 -235 -110 -19 -7 -44 -17 -55 -22 -11 -5 -49 -20 -85                 -33 -36 -13 -101 -41 -145 -61 -44 -20 -154 -68 -245 -107 -91 -39 -186 -81                 -212 -94 l-48 -24 0 -325 0 -325 281 0 280 0 -7 174 -7 175 39 16 c21 9 84 29                 139 45 55 16 132 38 170 50 39 12 111 32 160 45 168 43 187 55 310 205 61 73                 136 169 167 214 32 44 77 108 101 141 24 33 86 123 137 200 51 77 135 201 185                 276 88 131 91 137 78 163 -16 31 -17 31 -71 4z"/>
</g>
</svg>

**Comment by SpEcHiDe** [comment]
![SVG_Logo](https://raw.githubusercontent.com/fosscell/fossmeet17/f3a2033a080395f48f91f41667832f9eb5143eee/img/logo.svg) 
By @ronnel
