### ISSUE TITLE
Previous Events

### ISSUE THREAD

**Issue by SpEcHiDe** [fosscell/2017#15]
@fosscell/content2017  please create a write up for the previous events consistent with the current photos in the webpage.

P.S.: You may suggest to change the photos if there exists better quality photos than the current ones.

**Comment by SpEcHiDe** [comment]
I accidentally compressed using Google Developers Page Speed test webpage. The image width and height were reduced. This might be the working version 7f2c68d9fe1138565adf92347c9f6dc49cb05cb8. If possible, can you revert back to this version?  
@fosscell/web2017  @fosscell/design17

**Comment by aashishsatya** [comment]
Where will the write-ups go? How long do they have to be?
