### ISSUE TITLE
Suggestion Required

### ISSUE THREAD

**Issue by SpEcHiDe** [fosscell/2017#18]
@fosscell/content2017  @fosscell/design17  

What should be included in the section "Reach Us" ?

As @pbhopalka rightly said, we do not need the map for this version of the webpage, please comment appropriately.

**Comment by pbhopalka** [comment]
I think our contact details will be fine. Rather than simply writing down the email id and a phone number, I suggest we write a sentence in a bit fashionly font "If you have any queries, we are open to every questions/ suggestions. Shoot an email at <email>"

One section that just says this.
