### ISSUE TITLE
Sponsors images are not displaying.

### ISSUE THREAD

**Issue by yashhere** [fosscell/2017#20]
![capture](https://cloud.githubusercontent.com/assets/13733968/18725073/6af69a80-805c-11e6-8dbe-f292e3a58a0f.JPG)

**Comment by SpEcHiDe** [comment]
@fosscell/web2017 any ideas?

**Comment by SpEcHiDe** [comment]
temporary FIX! so closing this for now!

**Comment by amaljose96** [comment]
Set width and height manually in css

**Comment by SpEcHiDe** [comment]
![screenshot from 2016-09-28 22-27-43](https://cloud.githubusercontent.com/assets/6317196/18923769/443c6108-85cb-11e6-8189-e73df2774ce9.png)

I think it is because some JavaScript resource that is being used is dynamically appending a <style> in the <head>

**Comment by SpEcHiDe** [comment]
The issue is not solved. Apparently, only @yash2696 will know how to solve it!

**Comment by SpEcHiDe** [comment]
turns out that it was an issue with the [adblock extension](https://github.com/chrisaljoudi/uBlock/issues/161)

**Comment by yashhere** [comment]
I thought that this extension only blocks the font awesome social media icons.
