### ISSUE TITLE
About the organizations that support the cause !

### ISSUE THREAD

**Issue by SpEcHiDe** [fosscell/2017#6]

**Comment by simsarulhaqv** [comment]
Can you make that statement more meaningful?

**Comment by simsarulhaqv** [comment]
You mean sponsors?

**Comment by SpEcHiDe** [comment]
@fosscell/content2017

**Comment by SpEcHiDe** [comment]
@fosscell/design17  the logos of the previous year sponsors are not proper. please fix the images.
